application: lightning-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /api/.*
  script: api.py
  secure: always
- url: /tasks/*
  script: tasks.py
  login: admin

builtins:
- datastore_admin: on
